shim.coffee
shim.js
test/page.coffee

Without this function it was impossible to catch a Parser Error.

Added missing onError handler.

---

phantom.coffee
phantom.js

returning an exit code other than 0 is actually useful

fixed: don't assert child-process exit code

---

.travis.yml

Added build chain config for Node GYP in Node 4.x so that `npm install` will succeed as per https://github.com/substack/dnode/pull/174

Add CI test for node `v4` and `latest`

---

package.json
phantom.coffee
test/closing.coffee

Following #316, with @jazzzz input, a process should exit on ``` SIGINT ```.
With this, phantom will run ``` process.exit ``` if the only callbacks for signals are its own.

Process exits when there are no user defined signal handlers

---

README.markdown

Hey guys, 
I used the flag syntax from the doc to prevent parent process from exiting on segfault, but it doesn't work, looks like it just wants an object. 
Error:
Jan 23 00:14:05 vagrant-ubuntu-trusty-64 ts-cs[8373]: [/node_modules/phantom/phantom.js:181] phantom stderr: Can't open 'flags'
Code:
```
create: ->
args = []
options = {}
for arg in arguments
switch typeof arg
when 'function' then cb = arg
when 'string' then args.push arg
when 'object' then options = arg
if typeof options.parameters is 'object'
for key, value of options.parameters
args.push '--'+key+'='+value
options.path ?= ''
options.binary ?= options.path+'phantomjs'
options.port ?= 0
options.hostname ?= ‘localhost’
```

Code Doesn't match documentation

---

src/shim.js

Continuous reads prevent the event-queue from processing JavaScript on the webpage (including DOM changes). 

Prevent blocking reads from clogging event-queue.

---

README.md
src/shim.js
src/spec/page_spec.js

```js
var phantom = require('phantom');
phantom.create().then(function(ph) {
ph.createPage().then(function(page) {
var test = 123;
var property2 = 'foobar';
page.property('onResourceRequested', function(requestData, request, a, b, c) {
console.log(requestData.id, a, b, c);
}, test, property2, {fooBar: true});
page.open('http://amirraminfar.com', function(status) {
ph.exit();
});
});
});
```
makes it so the above is possible. 

Fixes #383 by adding proxy around callbacks

---

src/page.js
src/spec/page_spec.js

Add setContent command, test both content and URL in page_spec.
We need it since setContent can't be replaced by property('content') because property('url') is read only.
No docs since it already says “most method calls”.

Add page.setContent command

---

README.md
src/out_object.js
src/phantom.js
src/shim.js
src/spec/out_object_spec.js

This pull request add functionality to pass data back into node. Here is sample code:
```js
var reqPageUrl = 'http://amirraminfar.com/';
var phantom = require('phantom');
phantom.create().then(function(ph) {
ph.createPage().then(function(page) {
var outObj = ph.createOutObject(); // <-- use this special object to return data back to node
page.property('onResourceReceived', function(resource, reqPageUrl, out) {
if (resource.url === reqPageUrl) {
console.log('resource.url', resource.url);
out.url = resource.status;
}
}, reqPageUrl, outObj).then(function() {
return page.open(reqPageUrl);
}).then(function(status) {
console.log('status', status);
return outObj.property('url');
}).then(function(url) {
console.log('url', url);
ph.exit();
}).catch(function(e) {
console.error(e)
});
});
});
``` …

Adds OutObject to be able to pass data back in to node

---

README.md
package.json
src/page.js
src/phantom.js
src/shim.js
src/spec/page_spec.js

I added a mechanism to add event listeners to a phantom page. These event listeners would run in node runtime by default (and would support closures and all Js functions goodness). 
I added the `#on(event, runOnPhantom, callback, args**)` method to the `Page` class, as well as the `#off(event)` method. The off method remove all events listeners. 
Also I added the on method to the Phantom class the methods `#on()` and `#off()`, but it will set the events to a specified target (by its id).
If you use `property` to set an event, then it would override all the events set using `#on()`. If you use `#on()` again, it would restore all the event listeners set by `#on()`, and the one set with property would be overwritten. 
It works the same as property, for the functions when you specify you want …

Made that page events could be run in node runtime

---

README.md
package.json
src/page.js
src/spec/page_spec.js

Support for [page#switchToFrame](http://phantomjs.org/api/webpage/method/switch-to-frame.html) and [page#switchToMainFrame](http://phantomjs.org/api/webpage/method/switch-to-main-frame.html).
I had to include `babel-core `in dev-dependencies of the package.json because my tests would not run without it. We can remove it from the PR if necessary.

Add support for page#switchToFrame and page#switchToMainFrame

---

src/phantom.js
src/spec/page_spec.js

This pull requests does a few things: 
- Cleans up logging so that what using `page.property = ...` throws a warning. 
- Cleans up spaces 
- ~~Force kill phantomjs process~~ Looks like this breaks travis. 

Clean up logging

---

src/page.js
src/spec/page_spec.js

The commit adds support for [page#reload()](http://phantomjs.org/api/webpage/method/reload.html). As of right now you need to evaluate the function 'location.reload()' in the context of the web page to perform a reload.

Add support for page#reload

---

src/page.js
src/shim.js
src/spec/page_spec.js

This pull request addresses issue https://github.com/amir20/phantomjs-node/issues/487, and it:
- adds `page.invokeAsyncMethod`, which invokes any asynchronous method ('includeJs', 'open', etc.)
- adds `page.invokeMethod`, which invokes any method
- adds `page.defineMethod`, which defines a method
- reimplements `property`, `setting` as commands rather than methods 
- binds the built-in/native methods to `invokeAsyncMethod`, and `invokeMethod`
- removes some deprecated code
Examples:
```js
'use strict';
const phantomjs = require('phantom');
let page;
let phantom;
phantomjs.create().then(function (instance) {
phantom = instance;
return phantom.createPage();
}).then(function (instance) {
page = instance;
return page.defineMethod('exists', function (selector, callback) {
var element = …
```

Add ability to define and invoke methods (#487)

---

src/page.js
src/phantom.js
src/shim.js
src/spec/page_spec.js

This pull request binds `phantom.exit` to `invokeMethod`, which means that all methods are now explicitly invoked via `invokeAsyncMethod` or `invokeMethod`, and that the block of code that implicitly invoked methods can be removed. It also updates the obsolete 'Page#reject' test.

All methods are explicitly invoked via invokeAsyncMethod or invokeMethod.

---

src/page.js
src/spec/page_spec.js

I added `Page#setProxy`, on behalf of @wesleymilan.
The test uses the server as a proxy, so http://phantomjs.org/ won't actually be opened/requested, as the server immediately responds 'hi, http://phantomjs.org/' instead.

Add Page#setProxy

---

README.md
src/index.js
src/phantom.js
src/spec/phantom_spec.js

Added possibility of using custom PhantomJS path by adding 'config' object to Phantom c-tor (with 'phantomPath' property inside).
Added docs and tests.
Tested in production, works well even with older PhantomJS binaries (namely 1.9.8 from npm package phantomjs@1.9.20)

Add custom PhantomJS path support by passing it in config object to phantom.create()

---

src/shim.js
src/spec/page_spec.js

phantom-node currently hangs indefinitely if you try to pass an argument of `null` or `undefined` to the `page#evaluate` method. For example:
```
var Phantom = require('phantom');
var sitepage = null;
var phInstance = null;
Phantom.create()
.then(instance => {
phInstance = instance;
return instance.createPage();
}).then(page => {
sitepage = page;
return page.open('http://httpbin.org/get');
}).then(status => {
sitepage.evaluate(function(val) {
return "Hello world! Parameter value = "+val;
}, null).then(function(result){
console.log(result);
});
})
.then(() => {
sitepage.close();
phInstance.exit();
})
.catch(error => {
console.log(error);
phInstance.exit();
});;
```
This PR updates the `transform` method to properly handle both `null` and `undefined`.

Fix hanging crash when passing null to page#evaluate

---

src/shim.js
src/shim_support.js

Added Function.prototype.bind fallback (based on [Polyfill implementation on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill)) for compatibility with PhantomJS 1.9.x and earlier.
This is a much cleaner solution to issue raised in #508.
Test wasn't added as it would require adding yet another PhantomJS binary to devDependencies (and pulling additional ~60MBs).
* ~~[ ] New tests have been added~~ See note above
* ~~[ ] Documentation has been updated~~ N/A

shim.js: add Function.prototype.bind fallback

---

src/phantom.js

I noticed that `command.deferred` was set before `command ` was stringified, and, consequently, sent to PhantomJS unnecessarily.
I also fixed the detection of arrow functions. According to the [documentation](http://wiki.ecmascript.org/doku.php?id=harmony:arrow_function_syntax) arrow functions lack a prototype. We can consequently detect arrow functions by checking if the variable:
1. is a function
2. lacks a prototype

Refactor Phantom#executeCommand, and fix detection of arrow functions

---

src/__test__/command.spec.js
src/command.js
src/out_object.js
src/util/random_id.js

`Math.random()` is of lower quality then `crypto.randomBytes()`, but is much faster and doesn't consume system's entropy.

Replace crypto.randomBytes() with Math.random() to address #563

---

.babelrc

This PR fixes babel warnings, that flood the logs during tests: 
```
We recommend using a string for minor/patch versions to avoid numbers like 6.10
getting parsed as 6.1, which can lead to unexpected behavior.
Warning, the following targets are using a decimal version:
node: 6.9
```
Example: https://travis-ci.org/amir20/phantomjs-node/jobs/237976527

Fix babel warnings

---

decls/logger.js
src/__test__/index.spec.js
src/__test__/phantom.spec.js
src/phantom.js

Another approach for #683 with a refactor and skipping tests that always presume logger would be winston-like
* Allows logger to be anything other than object
* Doesn't change the original logger object when polyfilling debug/info methods
* Preserves `this` when calling methods on original logger object

fix: logger

---

README.md

The `Page` class does not define a `load` method as previously referenced in the documentation. Update the examples to instead reference the `open` method of that class.

Docs: correct method name

---

README.md
decls/config.js
src/__test__/index.spec.js
src/phantom.js

For some reason, I get the error:
```
Error: src/phantom.js:80
80:     this.logger.debug(`Starting ${phantomPath} ${args.join(' ')}`);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unused function argument
75:       debug: logger.debug ? (...msg) => logger.debug(...msg) : () => undefined,
^^^^^^^^^^^^^^^ function expects no arguments
```
When I try to remove line 81, or:
```
const pathToShim = path.normalize(`${__dirname}/shim/index.js`);  // eslint-disable-line 
```
from the file `src/phantom.js`. Do you have any idea why this would be?
This PR allows users to pass in where their shim/index.js file is located. This is useful when this library is being used in contexts such as AWS lambda, where the location `__dirname` will lead the program to is not correct.

Allowing custom shim path to be used during Phantom creation
