README.markdown

Added an npm badge for a quick synopsis of version info as well as linking to the npm repository instead of having to do a secondary search.

README: added npm badge

---

shim.coffee
shim.js

Fixes issue with onPageCreated not returning valid web_page object.

Fix for issue 300

---

package.json

this helps with compile error and Node.js v4.0.0.

upgrade shoe to 0.0.15

---

package.json

fresh off the press, dnode 1.2.2.  might as well resubmit.

bump dnode to 1.2.2, which plays nice with nodejs 4

---

phantom.coffee
samples/test_phantom.coffee
samples/test_phantom_10.coffee
samples/test_phantom_2.coffee
samples/test_phantom_3.coffee
samples/test_phantom_4.coffee
samples/test_phantom_5.coffee
samples/test_phantom_6.coffee
samples/test_phantom_7.coffee
samples/test_phantom_8.coffee
samples/test_phantom_9.coffee
shim.coffee
test/adv.coffee
test/basic.coffee
test/callbacks.coffee
test/closing.coffee
test/error.coffee
test/frames.coffee
test/page.coffee

reading through more of the code and fixed some stuff (see commit messages)

further pedantry

---

package.json
phantom.coffee

I defaulted `--web-security=no`. I think that's the right fix for now. Going to deploy 0.9.0

Defaults to web_security=no. Fixes #353, fixes #345, and #349

---

package.json
phantom.coffee

Better pull request - use prebuilt phantomjs if it is there.

resolves #355 - Adopt phantomjs-prebuilt

---

src/page.js
src/phantom.js
src/shim.js
src/spec/page_spec.js
src/spec/phantom_spec.js

Adds suports for multi pages.

---

package.json
src/phantom.js
src/spec/phantom_spec.js

Mocks tests to test create()

---

src/phantom.js
src/shim.js

Adds a heartbeat every 100ms. 

Fixes #369 by adding a heartbeat

---

gulpfile.babel.js
package.json
src/page.js
src/phantom.js
src/shim.js
src/spec/page_spec.js

Allows node to do `phantom.windowProperty('GLOBAL_VAR')`;

Adds eval for global space properties. 

---

src/phantom.js
src/shim.js
src/spec/page_spec.js

Fixes #415 by implementing phantom.callback

---

README.md

Changed readme file with sample that uses Promise in proper way (chaining instead of callbacks structure). You can [use this article](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html) for further research. I didn't add any tests because changed only readme file.

Changed readme to use promises chaining instead of callback-like style.

---

README.md

License link is broken

---

src/phantom.js
src/spec/phantom_spec.js

Checks to make sure phantomjs is valid path.

Makes sure that phantomjs.path is valid. Related to #506.

---

examples/simple.js
src/phantom.js

[Describe what this pull request does]

Throws error for arrow function. Related to #521

---

src/page.js
src/spec/page_spec.js

add the goBack() method to the page object

add the goBack() method to the page object

---

src/spec/page_spec.js

Fixes issue https://github.com/amir20/phantomjs-node/issues/528.

Fix test for Page#goBack (#528)

---

README.md
src/page.js
src/spec/page_spec.js

Added "evaluateAsync" method of PhantomJS.

evaluateAsync method

---

README.md
src/index.js
src/phantom.js
src/spec/phantom_spec.js

Changes from #529 have been brought here so I could clean it up a little. I have added param destructuring using ES6 syntax. 

Fixes #529 and adds logger override for the module

---

README.md
src/page.js
src/spec/page_spec.js

This PR adds the #uploadFile method on the Page to allow inserting files into file input fields. 

Add Page#uploadFile

---

.babelrc
.eslintignore
.flowconfig
.npmignore
decls/config.js
decls/logger.js
gulpfile.babel.js
package.json
src/__test__/command.spec.js
src/__test__/out_object.spec.js
src/__test__/page.evaluate.spec.js
src/__test__/page.event.spec.js
src/__test__/page.spec.js
src/command.js
src/index.js
src/out_object.js
src/page.js
src/phantom.js
yarn.lock

[Describe what this pull request does]

Adds flow check style to everything

---

README.md

"the events the events" → "the events"

Fixed a typo in README.MD

---

src/phantom.js

Fixes a bug when phantomjs exited unexpectedly. 

Fixes #573 by resolving all promises with an error

---

.editorconfig
.travis.yml
gulpfile.babel.js
package.json
yarn.lock

[Describe what this pull request does]

Cleans package json

---

src/phantom.js

Exit returns promise

---

.travis.yml
package.json
src/phantom.js
yarn.lock

Replaces `linerstream` with `split`. 

Tries to use split instead of split2 and may fix #551 and #585

---

README.md

Added a link to phantom-pool to README, hope that's ok. See https://github.com/amir20/phantomjs-node/issues/590

README: add "Pooling" section

---

.travis.yml

Adds codecov

---

package-lock.json

Adds `package-lock.json` which is the same as `yarn.lock` for people using npm5

Add `package-lock.json`

---

README.md
examples/async.js
examples/co.js
examples/out_obj.js
examples/render.js
examples/simple.js

[Describe what this pull request does]

Fixes examples

---

package-lock.json
package.json
src/phantom.js

Logger constructor has changed to `createLogger` and fixes node v10 packages. 

Attempts to fix broken log construcutor
